#!/bin/bash
# ============================================================
# AgentHub Production Deployment Script
# ============================================================
# Tested on: Ubuntu 24.04 LTS
#
# Usage:
#   wget -q https://your-repo/agenthub/deploy.sh && chmod +x deploy.sh && ./deploy.sh
#   OR copy this script to your server and run:
#     ./deploy.sh
#
# What it does:
#   1. Installs Docker & Docker Compose
#   2. Clones (or updates) the repository
#   3. Creates production .env file
#   4. Builds and starts containers
#   5. Configures Nginx + SSL (Let's Encrypt)
#   6. Sets up firewall (UFW)
# ============================================================

set -e

# ─── Colors ───────────────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

log_info()  { echo -e "${BLUE}[INFO]${NC}  $1"; }
log_ok()    { echo -e "${GREEN}[OK]${NC}   $1"; }
log_warn()  { echo -e "${YELLOW}[WARN]${NC}  $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }

# ─── Config ────────────────────────────────────────────────
APP_NAME="agenthub"
APP_DIR="/opt/agenthub"
GIT_REPO="${GIT_REPO:-}"
DOMAIN="${DOMAIN:-}"
EMAIL="${EMAIL:-admin@${DOMAIN:-localhost}}"
API_PORT="${API_PORT:-3001}"
WEB_PORT="${WEB_PORT:-3000}"
NGINX_SSL_PORT="${NGINX_SSL_PORT:-443}"

# ─── Parse Args ────────────────────────────────────────────
while [[ $# -gt 0 ]]; do
  case $1 in
    --repo)      GIT_REPO="$2";      shift 2 ;;
    --domain)    DOMAIN="$2";        shift 2 ;;
    --email)     EMAIL="$2";         shift 2 ;;
    --dir)       APP_DIR="$2";       shift 2 ;;
    *)           log_error "Unknown option: $1"; exit 1 ;;
  esac
done

# ─── Pre-flight Checks ─────────────────────────────────────
log_info "Pre-flight checks..."

# Running as root?
if [[ $EUID -ne 0 ]]; then
  log_error "This script must be run as root (use sudo)"
  exit 1
fi

# Domain required for SSL
if [[ -z "$DOMAIN" ]]; then
  log_warn "No domain provided. SSL certificate will be skipped."
  log_info "To enable HTTPS, run: $0 --domain yourdomain.com --email your@email.com"
fi

# ─── Step 1: Install Docker ────────────────────────────────
log_info "Step 1: Installing Docker..."

if command -v docker &> /dev/null; then
  log_ok "Docker already installed: $(docker --version)"
else
  curl -fsSL https://get.docker.com | sh
  systemctl enable docker
  systemctl start docker
  log_ok "Docker installed: $(docker --version)"
fi

if command -v docker-compose &> /dev/null || docker compose version &> /dev/null; then
  log_ok "Docker Compose available"
else
  log_info "Installing Docker Compose..."
  curl -fsSL "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  chmod +x /usr/local/bin/docker-compose
  log_ok "Docker Compose installed"
fi

# ─── Step 2: Prepare App Directory ────────────────────────
log_info "Step 2: Preparing application directory..."

if [[ -d "$APP_DIR" ]]; then
  log_info "Directory $APP_DIR already exists. Pulling latest changes..."
  cd "$APP_DIR"
  if [[ -n "$GIT_REPO" ]] && git remote -v &>/dev/null; then
    git pull origin main
  fi
else
  mkdir -p "$APP_DIR"
  if [[ -n "$GIT_REPO" ]]; then
    log_info "Cloning repository..."
    git clone "$GIT_REPO" "$APP_DIR"
    cd "$APP_DIR"
  else
    log_warn "No git repo specified and directory doesn't exist."
    log_info "Please place your AgentHub code in $APP_DIR"
    exit 1
  fi
fi

cd "$APP_DIR"

# ─── Step 3: Create Production .env ───────────────────────
log_info "Step 3: Creating production environment file..."

cat > "$APP_DIR/.env" << EOF
# ============================================================
# AgentHub Production Environment
# Generated by deploy.sh on $(date -u +%Y-%m-%d)
# ============================================================

# ── Required ──────────────────────────────────────────────
JWT_SECRET=$(openssl rand -base64 48 | tr -d '/+=' | head -c 64)

# ── Environment ───────────────────────────────────────────
NODE_ENV=production
PORT=${API_PORT}

# ── Database ──────────────────────────────────────────────
DATABASE_URL=libsql:file:/app/data/agenthub.db

# ── CORS (change to your domain in production) ───────────
ALLOWED_ORIGINS=${DOMAIN:+https://${DOMAIN}}

# ── OAuth (optional - fill in if using OAuth) ─────────────
# GITHUB_CLIENT_ID=your_github_client_id
# GITHUB_CLIENT_SECRET=your_github_client_secret
# GOOGLE_CLIENT_ID=your_google_client_id
# GOOGLE_CLIENT_SECRET=your_google_client_secret

# ── Email (optional) ───────────────────────────────────────
# SMTP_HOST=smtp.example.com
# SMTP_PORT=587
# SMTP_USER=your_smtp_user
# SMTP_PASSWORD=your_smtp_password
# SMTP_FROM=noreply@example.com

# ── Frontend URL (for OAuth redirects) ────────────────────
FRONTEND_URL=${DOMAIN:+https://${DOMAIN}}

# ── Build Args ────────────────────────────────────────────
NEXT_PUBLIC_API_URL=${DOMAIN:+https://${DOMAIN}}
NEXT_PUBLIC_APP_URL=${DOMAIN:+https://${DOMAIN}}
EOF

log_ok "Environment file created at $APP_DIR/.env"

# ─── Step 4: Build & Start Containers ────────────────────
log_info "Step 4: Building and starting containers..."

# Ensure data directory exists and has correct permissions
mkdir -p "$APP_DIR/data"
chmod 755 "$APP_DIR/data"

# Build without cache to ensure fresh build
docker-compose build --no-cache

# Start services
docker-compose up -d

# Wait for API to be healthy
log_info "Waiting for API to be healthy..."
for i in {1..30}; do
  if curl -sf http://localhost:${API_PORT}/health > /dev/null 2>&1; then
    log_ok "API is healthy"
    break
  fi
  if [[ $i -eq 30 ]]; then
    log_error "API failed to become healthy after 30 attempts"
    docker-compose logs api
    exit 1
  fi
  sleep 2
done

log_ok "All containers are running"
docker-compose ps

# ─── Step 5: Nginx + SSL ─────────────────────────────────
if [[ -n "$DOMAIN" ]]; then
  log_info "Step 5: Configuring Nginx + SSL for domain: $DOMAIN"

  # Install Nginx
  apt-get update -qq
  apt-get install -y -qq nginx certbot python3-certbot-nginx

  # Stop Nginx temporarily for certbot
  systemctl stop nginx || true

  # Create Nginx config
  cat > "/etc/nginx/sites-available/${APP_NAME}" << EOF
# HTTP -> HTTPS redirect
server {
    listen 80;
    server_name ${DOMAIN};
    return 301 https://\$host\$request_uri;
}

# HTTPS proxy to Docker containers
server {
    listen 443 ssl http2;
    server_name ${DOMAIN};

    # SSL Certificate (managed by Certbot)
    ssl_certificate /etc/letsencrypt/live/${DOMAIN}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/${DOMAIN}/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    # Security headers
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-XSS-Protection "1; mode=block" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;

    # Logging
    access_log /var/log/nginx/${APP_NAME}_access.log;
    error_log  /var/log/nginx/${APP_NAME}_error.log;

    # Gzip compression
    gzip on;
    gzip_vary on;
    gzip_min_length 1024;
    gzip_proxied any;
    gzip_types text/plain text/css text/xml text/javascript
               application/x-javascript application/xml application/javascript
               application/json application/rss+xml application/atom+xml
               image/svg+xml;

    # Max upload size
    client_max_body_size 100M;

    # Web: Next.js static files
    location / {
        proxy_pass http://127.0.0.1:${WEB_PORT};
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_cache_bypass \$http_upgrade;
        proxy_read_timeout 60s;
    }

    # API: Fastify backend
    location /api/ {
        proxy_pass http://127.0.0.1:${API_PORT};
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_cache_bypass \$http_upgrade;
        proxy_read_timeout 60s;
    }

    # WebSocket
    location /socket.io/ {
        proxy_pass http://127.0.0.1:${API_PORT};
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_read_timeout 86400;
    }

    # Health check endpoint
    location /health {
        proxy_pass http://127.0.0.1:${API_PORT}/health;
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
    }
}
EOF

  # Enable site
  ln -sf "/etc/nginx/sites-available/${APP_NAME}" "/etc/nginx/sites-enabled/${APP_NAME}"

  # Remove default
  rm -f /etc/nginx/sites-enabled/default

  # Test Nginx config
  nginx -t

  # Obtain SSL certificate
  certbot --nginx -d "$DOMAIN" --noninteractive --agree-tos -m "$EMAIL"

  # Auto-renewal for Certbot
  cat > /etc/cron.d/certbot-renew << EOF
0 */12 * * * root certbot renew --quiet --deploy-hook "systemctl reload nginx"
EOF

  # Start Nginx
  systemctl enable nginx
  systemctl start nginx

  log_ok "Nginx + SSL configured for https://${DOMAIN}"
else
  log_warn "Step 5: Skipped (no domain provided)"
fi

# ─── Step 6: Firewall ──────────────────────────────────────
log_info "Step 6: Configuring firewall (UFW)..."

if command -v ufw &> /dev/null; then
  ufw --force enable
  ufw allow ssh
  ufw allow http
  ufw allow https
  ufw reload
  log_ok "Firewall configured (SSH, HTTP, HTTPS open)"
else
  log_warn "UFW not available, skipping firewall setup"
fi

# ─── Step 7: Systemd Service ─────────────────────────────
log_info "Step 7: Setting up systemd service for auto-start..."

cat > "/etc/systemd/system/${APP_NAME}.service" << EOF
[Unit]
Description=AgentHub AI Agent Community Platform
Requires=docker.service
After=network-online.target docker.service

[Service]
Type=oneshot
RemainAfterExit=yes
WorkingDirectory=${APP_DIR}
ExecStart=/usr/local/bin/docker-compose up -d
ExecStop=/usr/local/bin/docker-compose down
TimeoutStartSec=0
Restart=on-failure
RestartSec=10

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable "${APP_NAME}"
log_ok "Systemd service installed: ${APP_NAME}"

# ─── Step 8: Database Migration ────────────────────────────
log_info "Step 8: Checking database..."
if curl -sf http://localhost:${API_PORT}/health > /dev/null 2>&1; then
  log_ok "Database is ready"
else
  log_warn "Database may need migration. Run manually: docker-compose exec api pnpm --filter @agenthub/api db:migrate"
fi

# ─── Final Status ─────────────────────────────────────────
echo ""
echo "============================================================"
echo "  🎉 AgentHub Deployment Complete!"
echo "============================================================"
echo ""
echo "  App Directory : $APP_DIR"
echo "  Web (HTTP)   : http://localhost:${WEB_PORT}"
echo "  API          : http://localhost:${API_PORT}"
echo "  API Docs     : http://localhost:${API_PORT}/docs"
echo "  Health       : http://localhost:${API_PORT}/health"
echo ""
if [[ -n "$DOMAIN" ]]; then
  echo "  Domain       : https://${DOMAIN}"
  echo "  SSL          : ✅ Enabled (Let's Encrypt)"
fi
echo ""
echo "  Useful Commands:"
echo "    cd $APP_DIR"
echo "    docker-compose logs -f api    # View API logs"
echo "    docker-compose logs -f web    # View Web logs"
echo "    docker-compose restart        # Restart services"
echo "    ./deploy.sh                   # Redeploy (pull + rebuild)"
echo ""
echo "============================================================"
