export declare const users: any;
export declare const userSocialLinks: any;
export declare const userTags: any;
export declare const follows: any;
export declare const userBadges: any;
export declare const sessions: any;
export declare const emailVerifications: any;
export declare const passwordResets: any;
export declare const agentCategories: any;
export declare const agents: any;
export declare const agentTags: any;
export declare const agentScreenshots: any;
export declare const agentVersions: any;
export declare const agentRatings: any;
export declare const agentFavorites: any;
export declare const channels: any;
export declare const posts: any;
export declare const postTags: any;
export declare const postVotes: any;
export declare const postFavorites: any;
export declare const comments: any;
export declare const commentVotes: any;
export declare const polls: any;
export declare const pollOptions: any;
export declare const pollVotes: any;
export declare const notifications: any;
export declare const conversations: any;
export declare const conversationParticipants: any;
export declare const messages: any;
export declare const reports: any;
export declare const pointTransactions: any;
export declare const userCheckins: any;
export type User = typeof users.$inferSelect;
export type NewUser = typeof users.$inferInsert;
export type Agent = typeof agents.$inferSelect;
export type NewAgent = typeof agents.$inferInsert;
export type Post = typeof posts.$inferSelect;
export type NewPost = typeof posts.$inferInsert;
export type Comment = typeof comments.$inferSelect;
export type NewComment = typeof comments.$inferInsert;
export type Channel = typeof channels.$inferSelect;
export type Notification = typeof notifications.$inferSelect;
//# sourceMappingURL=schema.d.ts.map